// Jobs Action Types

// Candidate - Search & Browse Jobs
export const JOBS_SEARCH_REQUEST = 'JOBS_SEARCH_REQUEST';
export const JOBS_SEARCH_SUCCESS = 'JOBS_SEARCH_SUCCESS';
export const JOBS_SEARCH_FAILURE = 'JOBS_SEARCH_FAILURE';

export const JOBS_GET_LATEST_REQUEST = 'JOBS_GET_LATEST_REQUEST';
export const JOBS_GET_LATEST_SUCCESS = 'JOBS_GET_LATEST_SUCCESS';
export const JOBS_GET_LATEST_FAILURE = 'JOBS_GET_LATEST_FAILURE';

export const JOBS_GET_DETAIL_REQUEST = 'JOBS_GET_DETAIL_REQUEST';
export const JOBS_GET_DETAIL_SUCCESS = 'JOBS_GET_DETAIL_SUCCESS';
export const JOBS_GET_DETAIL_FAILURE = 'JOBS_GET_DETAIL_FAILURE';

export const JOBS_GET_FILTER_OPTIONS_REQUEST = 'JOBS_GET_FILTER_OPTIONS_REQUEST';
export const JOBS_GET_FILTER_OPTIONS_SUCCESS = 'JOBS_GET_FILTER_OPTIONS_SUCCESS';
export const JOBS_GET_FILTER_OPTIONS_FAILURE = 'JOBS_GET_FILTER_OPTIONS_FAILURE';

// Candidate - Saved Jobs
export const JOBS_GET_SAVED_REQUEST = 'JOBS_GET_SAVED_REQUEST';
export const JOBS_GET_SAVED_SUCCESS = 'JOBS_GET_SAVED_SUCCESS';
export const JOBS_GET_SAVED_FAILURE = 'JOBS_GET_SAVED_FAILURE';

export const JOBS_TOGGLE_SAVED_REQUEST = 'JOBS_TOGGLE_SAVED_REQUEST';
export const JOBS_TOGGLE_SAVED_SUCCESS = 'JOBS_TOGGLE_SAVED_SUCCESS';
export const JOBS_TOGGLE_SAVED_FAILURE = 'JOBS_TOGGLE_SAVED_FAILURE';

// Recruiter - CRUD Jobs
export const RECRUITER_JOBS_LIST_REQUEST = 'RECRUITER_JOBS_LIST_REQUEST';
export const RECRUITER_JOBS_LIST_SUCCESS = 'RECRUITER_JOBS_LIST_SUCCESS';
export const RECRUITER_JOBS_LIST_FAILURE = 'RECRUITER_JOBS_LIST_FAILURE';

export const RECRUITER_JOB_DETAIL_REQUEST = 'RECRUITER_JOB_DETAIL_REQUEST';
export const RECRUITER_JOB_DETAIL_SUCCESS = 'RECRUITER_JOB_DETAIL_SUCCESS';
export const RECRUITER_JOB_DETAIL_FAILURE = 'RECRUITER_JOB_DETAIL_FAILURE';

export const RECRUITER_JOB_CREATE_REQUEST = 'RECRUITER_JOB_CREATE_REQUEST';
export const RECRUITER_JOB_CREATE_SUCCESS = 'RECRUITER_JOB_CREATE_SUCCESS';
export const RECRUITER_JOB_CREATE_FAILURE = 'RECRUITER_JOB_CREATE_FAILURE';

export const RECRUITER_JOB_UPDATE_REQUEST = 'RECRUITER_JOB_UPDATE_REQUEST';
export const RECRUITER_JOB_UPDATE_SUCCESS = 'RECRUITER_JOB_UPDATE_SUCCESS';
export const RECRUITER_JOB_UPDATE_FAILURE = 'RECRUITER_JOB_UPDATE_FAILURE';

export const RECRUITER_JOB_DELETE_REQUEST = 'RECRUITER_JOB_DELETE_REQUEST';
export const RECRUITER_JOB_DELETE_SUCCESS = 'RECRUITER_JOB_DELETE_SUCCESS';
export const RECRUITER_JOB_DELETE_FAILURE = 'RECRUITER_JOB_DELETE_FAILURE';

// Clear
export const CLEAR_JOB_DETAIL = 'CLEAR_JOB_DETAIL';
export const CLEAR_JOBS_ERROR = 'CLEAR_JOBS_ERROR';
export const CLEAR_JOBS_MESSAGE = 'CLEAR_JOBS_MESSAGE';
