// Applications Action Types

// Candidate - Apply & Manage Applications
export const APPLICATION_APPLY_REQUEST = 'APPLICATION_APPLY_REQUEST';
export const APPLICATION_APPLY_SUCCESS = 'APPLICATION_APPLY_SUCCESS';
export const APPLICATION_APPLY_FAILURE = 'APPLICATION_APPLY_FAILURE';

export const APPLICATION_GET_LIST_REQUEST = 'APPLICATION_GET_LIST_REQUEST';
export const APPLICATION_GET_LIST_SUCCESS = 'APPLICATION_GET_LIST_SUCCESS';
export const APPLICATION_GET_LIST_FAILURE = 'APPLICATION_GET_LIST_FAILURE';

export const APPLICATION_CHECK_APPLIED_REQUEST = 'APPLICATION_CHECK_APPLIED_REQUEST';
export const APPLICATION_CHECK_APPLIED_SUCCESS = 'APPLICATION_CHECK_APPLIED_SUCCESS';
export const APPLICATION_CHECK_APPLIED_FAILURE = 'APPLICATION_CHECK_APPLIED_FAILURE';

export const APPLICATION_CANCEL_REQUEST = 'APPLICATION_CANCEL_REQUEST';
export const APPLICATION_CANCEL_SUCCESS = 'APPLICATION_CANCEL_SUCCESS';
export const APPLICATION_CANCEL_FAILURE = 'APPLICATION_CANCEL_FAILURE';

// Recruiter - Manage Applications
export const RECRUITER_APPLICATION_LIST_REQUEST = 'RECRUITER_APPLICATION_LIST_REQUEST';
export const RECRUITER_APPLICATION_LIST_SUCCESS = 'RECRUITER_APPLICATION_LIST_SUCCESS';
export const RECRUITER_APPLICATION_LIST_FAILURE = 'RECRUITER_APPLICATION_LIST_FAILURE';

export const RECRUITER_APPLICATION_JOB_LIST_REQUEST = 'RECRUITER_APPLICATION_JOB_LIST_REQUEST';
export const RECRUITER_APPLICATION_JOB_LIST_SUCCESS = 'RECRUITER_APPLICATION_JOB_LIST_SUCCESS';
export const RECRUITER_APPLICATION_JOB_LIST_FAILURE = 'RECRUITER_APPLICATION_JOB_LIST_FAILURE';

export const RECRUITER_APPLICATION_DETAIL_REQUEST = 'RECRUITER_APPLICATION_DETAIL_REQUEST';
export const RECRUITER_APPLICATION_DETAIL_SUCCESS = 'RECRUITER_APPLICATION_DETAIL_SUCCESS';
export const RECRUITER_APPLICATION_DETAIL_FAILURE = 'RECRUITER_APPLICATION_DETAIL_FAILURE';

export const RECRUITER_APPLICATION_UPDATE_STATUS_REQUEST = 'RECRUITER_APPLICATION_UPDATE_STATUS_REQUEST';
export const RECRUITER_APPLICATION_UPDATE_STATUS_SUCCESS = 'RECRUITER_APPLICATION_UPDATE_STATUS_SUCCESS';
export const RECRUITER_APPLICATION_UPDATE_STATUS_FAILURE = 'RECRUITER_APPLICATION_UPDATE_STATUS_FAILURE';

// Clear
export const CLEAR_APPLICATION_ERROR = 'CLEAR_APPLICATION_ERROR';
export const CLEAR_APPLICATION_MESSAGE = 'CLEAR_APPLICATION_MESSAGE';
