// Fetch Notifications
export const NOTIFICATION_FETCH_REQUEST = 'NOTIFICATION_FETCH_REQUEST';
export const NOTIFICATION_FETCH_SUCCESS = 'NOTIFICATION_FETCH_SUCCESS';
export const NOTIFICATION_FETCH_FAILURE = 'NOTIFICATION_FETCH_FAILURE';

// Mark as Read
export const NOTIFICATION_MARK_READ_REQUEST = 'NOTIFICATION_MARK_READ_REQUEST';
export const NOTIFICATION_MARK_READ_SUCCESS = 'NOTIFICATION_MARK_READ_SUCCESS';
export const NOTIFICATION_MARK_READ_FAILURE = 'NOTIFICATION_MARK_READ_FAILURE';

// Delete Notification
export const NOTIFICATION_DELETE_REQUEST = 'NOTIFICATION_DELETE_REQUEST';
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS';
export const NOTIFICATION_DELETE_FAILURE = 'NOTIFICATION_DELETE_FAILURE';

// Set Local Notifications
export const NOTIFICATION_SET_LOCAL = 'NOTIFICATION_SET_LOCAL';
